Mode = 0   # 0 for master, 1 for slave

Port = 2000 # kvstore run port

ENABLE_MODULE_SYNC = 0 

ENABLE_MODULE_SAVE = 0

ENABLE_MODULE_LOG = 0

Master_ip = 192.168.184.138 # full sync ip

Master_port = 2000 # full sync ip

Rdma_server_ip = 192.168.184.138 # rdma communication ip

Rdma_port = 9999 # rdma communication port

Agent_ip = 192.168.184.138 # incr sync ip
 
Agent_port = 2200  # incr sync port